# Site settings
title: Smartalk
title_separator: " | "
name: Smartalk
subtitle: "טלפוניה חכמה, תוצאות מנצחות!"
description: "Smartalk - טלפוניה חכמה, תוצאות מנצחות!"
url: "smartalk.ovh" # בהמשך תכניס כאן את הדומיין שלך אם יש (למשל: https://smartalk.co.il)
baseurl: "" # השאר ריק אם האתר ברמת root
logo: "https://raw.githubusercontent.com/David-wacholder/smartalk.ovh/refs/heads/main/assets/images/%E2%80%8F%E2%80%8Fsmartalk-logo.png"
masthead_title: "Smartalk"

# הגדרות אזור ושפה
locale: "he-IL"

# הגדרות RTL
direction: rtl # שינוי מ-ltr ל-rtl עבור תמיכה בעברית

# Author (לא חובה אבל מוסיף פרטים באזורים מסוימים)
author:
  name: Smartalk
  avatar: "/assets/images/smartalk-logo.png" # עדכון נתיב לתיקייה הנכונה
  bio: "טלפוניה חכמה, תוצאות מנצחות!"
  location: "Israel"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# צבעי מותג מותאמים אישית (נשתמש בזה בהמשך בקוד CSS)
color_scheme:
  primary: "#0A2647"     # כחול כהה
  accent: "#40E0D0"      # טורקיז
  text: "#333333"        # טקסט כהה
  background: "#ffffff"  # רקע לבן

# הגדרות פונטים
font_family: '"Heebo", "Assistant", sans-serif'

# Build settings
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
markdown: kramdown
highlighter: rouge

# Navigation
header_pages:
  - index.md
  - about.md
  - contact.md

# Custom Colors
minimal_mistakes_skin: "default" # נשאיר את הבסיס ונעדכן דרך CSS מותאם אישית

# Social (אם תרצה בהמשך)
# social:
#   twitter: your_twitter
#   linkedin: your_linkedin

# Analytics (לא חובה כרגע)
# google_analytics: UA-XXXXXXXX-X

# Defaults (מאפשר שימוש בפריסה אחידה לכל הקבצים)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
      classes: wide
      toc: false
      toc_label: "תוכן העמוד"
      toc_icon: "list"
